import './fonts/montseratt/Montserrat-Regular.ttf'
import './fonts/montseratt/Montserrat-Light.ttf'
import './fonts/montseratt/Montserrat-ExtraBold.ttf'
import './fonts/montseratt/Montserrat-Bold.ttf'
import './fonts/montseratt/Montserrat-SemiBold.ttf'
import './fonts/montseratt/Montserrat-Medium.ttf'
